### ISSUE TITLE
Exclude current product from suggested items

### ISSUE THREAD

**Issue by jgteske** [ellen-ls/E-commerce-Fullstack#1]
https://github.com/ellen-ls/E-commerce-Fullstack/blob/bd85d71535bfaf1f49792494da673e1bc9e5df95/ecommerce-store/app/(routes)/product/%5BproductId%5D/page.tsx#L18-L20

Change these lines and then it should exclude the current product.

```ts
  var suggestedProducts = await getProducts({
    categoryId: product?.category?.id,
  });
  suggestedProducts = suggestedProducts.filter(function (obj) {
    return obj.id !== product.id;
  });
```

**Comment by ellen-ls** [comment]
fixed
